name: Scheduled release of all packages

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
    inputs:
      library:
        description: "Library to build and test."

jobs:
  # base build
  build_base:
    if: >-
      github.repository == 'fem-on-colab/fem-on-colab' && (
        github.event_name == 'schedule' || github.event.inputs.library == 'base'
      )
    uses: fem-on-colab/fem-on-colab/.github/workflows/docker_base.yml@ldpreload
    secrets:
      CI_REGISTRY_USER: ${{ secrets.CI_REGISTRY_USER }}
      CI_REGISTRY_PASSWORD: ${{ secrets.CI_REGISTRY_PASSWORD }}

  # gcc build & test
  build_gcc:
    needs: [build_base]
    if: >-
      github.repository == 'fem-on-colab/fem-on-colab' && (
        (
          github.event_name == 'schedule' && needs.build_base.result == 'success'
        ) || (
          github.event_name != 'schedule' && github.event.inputs.library == 'gcc' && needs.build_base.result == 'skipped' && always()
        ) || (
          github.event_name != 'schedule' && github.event.inputs.library != 'gcc' && needs.build_base.result == 'success' && always()
        )
      )
    uses: fem-on-colab/fem-on-colab/.github/workflows/release.yml@ldpreload
    with:
      library: "gcc"
      task: "build"
      args: ""
    secrets:
      REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}

  test_gcc:
    needs: [build_gcc]
    if: >-
      github.repository == 'fem-on-colab/fem-on-colab' && (
        (
          github.event_name == 'schedule' && needs.build_gcc.result == 'success'
        ) || (
          github.event_name != 'schedule' && needs.build_gcc.result == 'success' && always()
        )
      )
    uses: fem-on-colab/fem-on-colab/.github/workflows/release.yml@ldpreload
    with:
      library: "gcc"
      task: "test"
      args: ""

  # Boost build & test
  build_boost:
    needs: [test_gcc]
    if: >-
      github.repository == 'fem-on-colab/fem-on-colab' && (
        (
          github.event_name == 'schedule' && needs.test_gcc.result == 'success'
        ) || (
          github.event_name != 'schedule' && github.event.inputs.library == 'boost' && needs.test_gcc.result == 'skipped' && always()
        ) || (
          github.event_name != 'schedule' && github.event.inputs.library != 'boost' && needs.test_gcc.result == 'success' && always()
        )
      )
    uses: fem-on-colab/fem-on-colab/.github/workflows/release.yml@ldpreload
    with:
      library: "boost"
      task: "build"
      args: ""
    secrets:
      REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}

  test_boost:
    needs: [build_boost]
    if: >-
      github.repository == 'fem-on-colab/fem-on-colab' && (
        (
          github.event_name == 'schedule' && needs.build_boost.result == 'success'
        ) || (
          github.event_name != 'schedule' && needs.build_boost.result == 'success' && always()
        )
      )
    uses: fem-on-colab/fem-on-colab/.github/workflows/release.yml@ldpreload
    with:
      library: "boost"
      task: "test"
      args: ""

  # mpi4py build & test
  build_mpi4py:
    needs: [test_gcc]
    if: >-
      github.repository == 'fem-on-colab/fem-on-colab' && (
        (
          github.event_name == 'schedule' && needs.test_gcc.result == 'success'
        ) || (
          github.event_name != 'schedule' && github.event.inputs.library == 'mpi4py' && needs.test_gcc.result == 'skipped' && always()
        ) || (
          github.event_name != 'schedule' && github.event.inputs.library != 'mpi4py' && needs.test_gcc.result == 'success' && always()
        )
      )
    uses: fem-on-colab/fem-on-colab/.github/workflows/release.yml@ldpreload
    with:
      library: "mpi4py"
      task: "build"
      args: ""
    secrets:
      REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}

  test_mpi4py:
    needs: [build_mpi4py]
    if: >-
      github.repository == 'fem-on-colab/fem-on-colab' && (
        (
          github.event_name == 'schedule' && needs.build_mpi4py.result == 'success'
        ) || (
          github.event_name != 'schedule' && needs.build_mpi4py.result == 'success' && always()
        )
      )
    uses: fem-on-colab/fem-on-colab/.github/workflows/release.yml@ldpreload
    with:
      library: "mpi4py"
      task: "test"
      args: ""

  # OCC build & test
  build_occ:
    needs: [test_gcc]
    if: >-
      github.repository == 'fem-on-colab/fem-on-colab' && (
        (
          github.event_name == 'schedule' && needs.test_gcc.result == 'success'
        ) || (
          github.event_name != 'schedule' && github.event.inputs.library == 'occ' && needs.test_gcc.result == 'skipped' && always()
        ) || (
          github.event_name != 'schedule' && github.event.inputs.library != 'occ' && needs.test_gcc.result == 'success' && always()
        )
      )
    uses: fem-on-colab/fem-on-colab/.github/workflows/release.yml@ldpreload
    with:
      library: "occ"
      task: "build"
      args: ""
    secrets:
      REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}

  test_occ:
    needs: [build_occ]
    if: >-
      github.repository == 'fem-on-colab/fem-on-colab' && (
        (
          github.event_name == 'schedule' && needs.build_occ.result == 'success'
        ) || (
          github.event_name != 'schedule' && needs.build_occ.result == 'success' && always()
        )
      )
    uses: fem-on-colab/fem-on-colab/.github/workflows/release.yml@ldpreload
    with:
      library: "occ"
      task: "test"
      args: ""

  # h5py build & test
  build_h5py:
    needs: [test_mpi4py]
    if: >-
      github.repository == 'fem-on-colab/fem-on-colab' && (
        (
          github.event_name == 'schedule' && needs.test_mpi4py.result == 'success'
        ) || (
          github.event_name != 'schedule' && github.event.inputs.library == 'h5py' && needs.test_mpi4py.result == 'skipped' && always()
        ) || (
          github.event_name != 'schedule' && github.event.inputs.library != 'h5py' && needs.test_mpi4py.result == 'success' && always()
        )
      )
    uses: fem-on-colab/fem-on-colab/.github/workflows/release.yml@ldpreload
    with:
      library: "h5py"
      task: "build"
      args: ""
    secrets:
      REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}

  test_h5py:
    needs: [build_h5py]
    if: >-
      github.repository == 'fem-on-colab/fem-on-colab' && (
        (
          github.event_name == 'schedule' && needs.build_h5py.result == 'success'
        ) || (
          github.event_name != 'schedule' && needs.build_h5py.result == 'success' && always()
        )
      )
    uses: fem-on-colab/fem-on-colab/.github/workflows/release.yml@ldpreload
    with:
      library: "h5py"
      task: "test"
      args: ""

  # pybind11 build & test
  build_pybind11:
    needs: [test_mpi4py]
    if: >-
      github.repository == 'fem-on-colab/fem-on-colab' && (
        (
          github.event_name == 'schedule' && needs.test_mpi4py.result == 'success'
        ) || (
          github.event_name != 'schedule' && github.event.inputs.library == 'pybind11' && needs.test_mpi4py.result == 'skipped' && always()
        ) || (
          github.event_name != 'schedule' && github.event.inputs.library != 'pybind11' && needs.test_mpi4py.result == 'success' && always()
        )
      )
    uses: fem-on-colab/fem-on-colab/.github/workflows/release.yml@ldpreload
    with:
      library: "pybind11"
      task: "build"
      args: ""
    secrets:
      REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}

  test_pybind11:
    needs: [build_pybind11]
    if: >-
      github.repository == 'fem-on-colab/fem-on-colab' && (
        (
          github.event_name == 'schedule' && needs.build_pybind11.result == 'success'
        ) || (
          github.event_name != 'schedule' && needs.build_pybind11.result == 'success' && always()
        )
      )
    uses: fem-on-colab/fem-on-colab/.github/workflows/release.yml@ldpreload
    with:
      library: "pybind11"
      task: "test"
      args: ""

  # petsc4py/real build & test
  build_petsc4py_real:
    needs: [test_h5py]
    if: >-
      github.repository == 'fem-on-colab/fem-on-colab' && (
        (
          github.event_name == 'schedule' && needs.test_h5py.result == 'success'
        ) || (
          github.event_name != 'schedule' && github.event.inputs.library == 'petsc4py' && needs.test_h5py.result == 'skipped' && always()
        ) || (
          github.event_name != 'schedule' && github.event.inputs.library != 'petsc4py' && needs.test_h5py.result == 'success' && always()
        )
      )
    uses: fem-on-colab/fem-on-colab/.github/workflows/release.yml@ldpreload
    with:
      library: "petsc4py"
      task: "build"
      args: "real"
    secrets:
      REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}

  test_petsc4py_real:
    needs: [build_petsc4py_real]
    if: >-
      github.repository == 'fem-on-colab/fem-on-colab' && (
        (
          github.event_name == 'schedule' && needs.build_petsc4py_real.result == 'success'
        ) || (
          github.event_name != 'schedule' && needs.build_petsc4py_real.result == 'success' && always()
        )
      )
    uses: fem-on-colab/fem-on-colab/.github/workflows/release.yml@ldpreload
    with:
      library: "petsc4py"
      task: "test"
      args: "real"

  # petsc4py/complex build & test
  build_petsc4py_complex:
    needs: [test_h5py]
    if: >-
      github.repository == 'fem-on-colab/fem-on-colab' && (
        (
          github.event_name == 'schedule' && needs.test_h5py.result == 'success'
        ) || (
          github.event_name != 'schedule' && github.event.inputs.library == 'petsc4py' && needs.test_h5py.result == 'skipped' && always()
        ) || (
          github.event_name != 'schedule' && github.event.inputs.library != 'petsc4py' && needs.test_h5py.result == 'success' && always()
        )
      )
    uses: fem-on-colab/fem-on-colab/.github/workflows/release.yml@ldpreload
    with:
      library: "petsc4py"
      task: "build"
      args: "complex"
    secrets:
      REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}

  test_petsc4py_complex:
    needs: [build_petsc4py_complex]
    if: >-
      github.repository == 'fem-on-colab/fem-on-colab' && (
        (
          github.event_name == 'schedule' && needs.build_petsc4py_complex.result == 'success'
        ) || (
          github.event_name != 'schedule' && needs.build_petsc4py_complex.result == 'success' && always()
        )
      )
    uses: fem-on-colab/fem-on-colab/.github/workflows/release.yml@ldpreload
    with:
      library: "petsc4py"
      task: "test"
      args: "complex"

  # vtk build & test
  build_vtk:
    needs: [test_h5py]
    if: >-
      github.repository == 'fem-on-colab/fem-on-colab' && (
        (
          github.event_name == 'schedule' && needs.test_h5py.result == 'success'
        ) || (
          github.event_name != 'schedule' && github.event.inputs.library == 'vtk' && needs.test_h5py.result == 'skipped' && always()
        ) || (
          github.event_name != 'schedule' && github.event.inputs.library != 'vtk' && needs.test_h5py.result == 'success' && always()
        )
      )
    uses: fem-on-colab/fem-on-colab/.github/workflows/release.yml@ldpreload
    with:
      library: "vtk"
      task: "build"
      args: ""
    secrets:
      REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}

  test_vtk:
    needs: [build_vtk]
    if: >-
      github.repository == 'fem-on-colab/fem-on-colab' && (
        (
          github.event_name == 'schedule' && needs.build_vtk.result == 'success'
        ) || (
          github.event_name != 'schedule' && needs.build_vtk.result == 'success' && always()
        )
      )
    uses: fem-on-colab/fem-on-colab/.github/workflows/release.yml@ldpreload
    with:
      library: "vtk"
      task: "test"
      args: ""

  # slepc4py/real build & test
  build_slepc4py_real:
    needs: [test_petsc4py_real]
    if: >-
      github.repository == 'fem-on-colab/fem-on-colab' && (
        (
          github.event_name == 'schedule' && needs.test_petsc4py_real.result == 'success'
        ) || (
          github.event_name != 'schedule' && github.event.inputs.library == 'slepc4py' && needs.test_petsc4py_real.result == 'skipped' && always()
        ) || (
          github.event_name != 'schedule' && github.event.inputs.library != 'slepc4py' && needs.test_petsc4py_real.result == 'success' && always()
        )
      )
    uses: fem-on-colab/fem-on-colab/.github/workflows/release.yml@ldpreload
    with:
      library: "slepc4py"
      task: "build"
      args: "real"
    secrets:
      REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}

  test_slepc4py_real:
    needs: [build_slepc4py_real]
    if: >-
      github.repository == 'fem-on-colab/fem-on-colab' && (
        (
          github.event_name == 'schedule' && needs.build_slepc4py_real.result == 'success'
        ) || (
          github.event_name != 'schedule' && needs.build_slepc4py_real.result == 'success' && always()
        )
      )
    uses: fem-on-colab/fem-on-colab/.github/workflows/release.yml@ldpreload
    with:
      library: "slepc4py"
      task: "test"
      args: "real"

  # slepc4py/complex build & test
  build_slepc4py_complex:
    needs: [test_petsc4py_complex]
    if: >-
      github.repository == 'fem-on-colab/fem-on-colab' && (
        (
          github.event_name == 'schedule' && needs.test_petsc4py_complex.result == 'success'
        ) || (
          github.event_name != 'schedule' && github.event.inputs.library == 'slepc4py' && needs.test_petsc4py_complex.result == 'skipped' && always()
        ) || (
          github.event_name != 'schedule' && github.event.inputs.library != 'slepc4py' && needs.test_petsc4py_complex.result == 'success' && always()
        )
      )
    uses: fem-on-colab/fem-on-colab/.github/workflows/release.yml@ldpreload
    with:
      library: "slepc4py"
      task: "build"
      args: "complex"
    secrets:
      REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}

  test_slepc4py_complex:
    needs: [build_slepc4py_complex]
    if: >-
      github.repository == 'fem-on-colab/fem-on-colab' && (
        (
          github.event_name == 'schedule' && needs.build_slepc4py_complex.result == 'success'
        ) || (
          github.event_name != 'schedule' && needs.build_slepc4py_complex.result == 'success' && always()
        )
      )
    uses: fem-on-colab/fem-on-colab/.github/workflows/release.yml@ldpreload
    with:
      library: "slepc4py"
      task: "test"
      args: "complex"

  # Warn if scheduled workflow is about to be disabled
  warn:
    runs-on: ubuntu-latest
    if: github.repository == 'fem-on-colab/fem-on-colab' && github.ref == 'refs/heads/main' && github.event_name == 'schedule'
    steps:
      - uses: actions/checkout@v3
      - name: Warn if scheduled workflow is about to be disabled
        uses: fem-on-colab/warn-workflow-about-to-be-disabled-action@main
        with:
          workflow-filename: schedule_all.yml
          days-elapsed: 28
